Stop filtering requests based on their presence in Slack
crownheightsaid/mutual-aid-app pull request #165
Opened 2020-10-23 19:47 UTC by jreinlein

Issue #157 

### Changes
- Removed `notInSlack` filter
- Added checks for `slackPermalink` in presentational component (when needed)
- A few minor fixes; sorry, couldn't help myself 😅 

### Testing
- Modified `requests.js` unit tests
- Checked table rows with and without the link
- Checked map popup with and without link

Screenshot:
![image](https://user-images.githubusercontent.com/7434338/97047270-b1cf9f00-1546-11eb-9a5c-ee77b50594bf.png)

2020-10-23 19:47 UTC, jreinlein commented on src/webapp/components/DeliveryTable.js
> +            <DeliveryTableRow row={row} key={row.Code} />
This will fix the console warnings about a lack of unique keys :) (`code` isn't a field, but `Code` is)

2020-10-23 21:53 UTC, piratefsh requested changes
Looking good, thanks for the improvements! I have a couple of changes requested, but the rest LGTM! Feel free to re-request review when you are ready.

2020-10-23 21:53 UTC, piratefsh commented on src/lib/airtable/tables/requests.js
>      fields.status_options.dispatchStarted,
Change requested: Now that we are only looking at requests in Delivery Needed state, we should remove `dispatchStarted` as an open state. Dispatch started requests may not have completed data for the request.

2020-10-26 19:43 UTC, jreinlein commented on src/api/delivery-needed/index.js
> +        slackPermalink: slackPermalink.permalink ?? "",
oh wow, good call-out. Thanks for that link, too, very informative. I'll revert.

2020-10-29 04:23 UTC, piratefsh approved these changes
latest changes lgtm! thanks for addressing those 👍

2020-10-29 14:05 UTC, merged